// Generated by CoffeeScript 1.3.3
(function() {
  var app, data, express, get, io, server;

  express = require('express');

  app = express();

  server = require('http').createServer(app);

  io = require('socket.io').listen(server);

  app.configure(function() {
    app.set('port', process.env.PORT || 13594);
    app.use(express.favicon());
    return app.use(express["static"](__dirname + '/public'));
  });

  app.get('/', function(req, res) {
    return res.sendfile(__dirname + '/public/index.html');
  });

  server.listen(app.get('port'), function() {
    return console.log("Listening on " + app.get('port'));
  });

  data = [
    {
      name: 'm',
      value: 100,
      color: '#FFF280'
    }, {
      name: 'r',
      value: 100,
      color: '#6EB7DB'
    }, {
      name: 'u',
      value: 100,
      color: '#DB7BB1'
    }
  ];

  get = function(name) {
    var x, _i, _len;
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      x = data[_i];
      if (x.name === name) {
        return x;
      }
    }
    return null;
  };

  io.sockets.on("connection", function(socket) {
    socket.emit("update", data);
    return socket.on("increase", function(name) {
      var x, _i, _len;
      if (!get(name)) {
        return;
      }
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        x = data[_i];
        if (x.name === name) {
          x.value += 2;
        } else {
          if (x.value > 0) {
            x.value -= 1;
          }
        }
      }
      return io.sockets.emit("update", data);
    });
  });

  io.configure(function() {
    io.set("transports", ["xhr-polling"]);
    return io.set("polling duration", 10);
  });

}).call(this);
